Repository udistrital/auditoria, pull requests merged in 2019-07, with the labels that each got.

#17 Correción de impresiones de fmt a Beego.Error
  middleware.go
  utils.go
Labels: help wanted

#18 Excepción Healthchecks e impresion cabecera
  middleware.go
Labels: bug

#19 Eliminación de impresión de cabecera
  middleware.go
Labels: bug

#20 se añade token al principio del log para eliminar información inneces…
  middleware.go
Labels: bug

#21 Se modifican los Scripts para creacion de tabla de consulta logs Audi…
  Scripts/DDL_APIS.sql
  Scripts/DDL_WSO2.sql
Labels: bug

#24 Actualización de Readme
  README.md
  interceptor.go
Labels: enhancement

#25 Cambio de archivo interceptos a master
  README.md
  interceptor.go
Labels: bug
